title: My Website
description: A simple personal website
baseurl: ""

markdown: kramdown
kramdown:
  math_engine: katex

defaults:
  -
    scope:
      path: "\_posts"
    values:
      layout: "posts"
      excerpt_separator: <!--more-->

exclude:
  - README.md
  - vendor/
